apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: learning-microservices

data:
  DISCOVERY_URL: 'http://discovery-service:4000'
  KAFKA_BROKERS: 'kafka:9092'
  GRPC_URL: '0.0.0.0:5001'
  PRODUCT_GRPC_URL: 'product-service:5001'
  PRODUCT_SERVICE_URL: 'http://product-service:3000'

  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: 'http://tempo:4318/v1/traces'
  OTEL_DEPLOYMENT_ENVIRONMENT: 'k8s'

  TIMEOUT_MS: '5000'
  MAX_ATTEMPTS: '3'
  FAILURE_THRESHOLD: '3'
  HALF_OPEN_AFTER_MS: '10000'
  BULKHEAD_LIMIT: '10'
  BULKHEAD_QUEUE: '10'

---
apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: learning-microservices

type: Opaque

stringData:
  JWT_SECRET: 'Pp9tTzVMYW7TLSVZ4FlbHqVDBqRHiFSSiypjAGyPBWE='

  DB_USER: 'postgres'
  DB_PASSWORD: 'postgres'