apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
  namespace: learning-microservices

spec:
  replicas: 1

  selector:
    matchLabels:
      app: discovery-service

  template:
    metadata:
      labels:
        app: discovery-service

      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "4000"
        prometheus.io/path: "/metrics"

    spec:
      containers:
        - name: discovery-service
          image: learning-microservices-discovery-service:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 4000

          envFrom:
            - configMapRef:
                name: config

            - secretRef:
                name: secret

          env:
            - name: OTEL_SERVICE_NAME
              value: discovery-service

---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: learning-microservices

spec:
  selector:
    app: discovery-service

  ports:
    - port: 4000
      targetPort: 4000
