{
 "title": "Microservices Observability",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "HTTP 5xx Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"5..\"}[1m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Average Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum[1m])) by (service) / sum(rate(http_server_requests_seconds_count[1m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{namespace=\"learning-microservices\"}"
    }
   ]
  }
 ]
}